<?php

/**
 * @var \Revision\Module1\Block\Display $block
 */

echo $block->sayHello();

?>


<style>
/*    table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
    td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
    tr:nth-child(even) { background-color: #dddddd; }
    .post-id{width:2%} .post-title{width:20%}
*/

    .column 
    {
        float: left;
        width: 50%;
        padding: 15px;
    }
    h1
    {
        color: black;
        font-family: verdana;
        font-size: 300%;
        text-align:center;
        font-weight: bold;
       /* margin-left: 100%;        */
    }
    p
    {
        color: black;
        font-family: verdana;
        font-size: 150%;
        text-align:left;
    }

    .box
    {
        position: relative;
        top:110px;
        left: 50%;
        transform: translate(-50%,-50%);
        width: 550px;
        height: 320px;
        box-sizing: border-box;
        background: rgba(0,0,0,0.1);
        border: 1px solid black;
    }
    
    img{border: 1px solid #ddd; border-radius: 4px; padding: 5px; width: 100px;}
    img:hover {box-shadow: 0 0 2px 1px rgba(0, 140, 186, 0.5);}


</style>

    <?php
        foreach ($block->getPostCollection() as $key=>$post)
            {
                echo '<div class="box">
                        <h1>'.$post->getTitle().'</h1>
                       '.$block->filterOutputHtml($post->getPostBody()).'<h3>'.$post->getAuthor().'</h3>
                        <h4>'.$post->getCreatedAt().'</h4>
                    </div>';
            }


    ?>
</body>
</html>